webcam:
  stream: /webcam/?action=stream
  snapshot: http://127.0.0.1:8080/?action=snapshot
  ffmpeg: /usr/bin/avconv
plugins:
  cura:
    cura_engine: /usr/local/bin/cura_engine
  discovery:
    publicPort: 80
  softwareupdate:
    checks:
      octoprint:
        current: c1355e4581c2f57db2b6eccb113a7ef4445a162a
      svgtogcode:
        current: 57222a8f0b14f3921cc1fdc7c33e0aa308ceb416
      lcd:
        current: 00d7f80b9664e0b7d60386ca7338ae31ce3e2083
      netconnectd:
        current: 314b108a29448712a4adaf9feaa92af9176e289a
system:
  actions:
  - name: Shutdown
    command: sudo shutdown -h now
    action: shutdown
    confirm: You are about to shutdown the system.
    async: true
    ignore: true
  - name: Reboot
    command: sudo shutdown -r now
    action: reboot
    confirm: You are about to reboot the system
    async: true
    ignore: true
  - name: Restart OctoPrint
    command: sudo service octoprint restart
    action: restart
    confirm: You are about to restart OctoPrint
    async: true
    ignore: true
