#!/usr/bin/env bash
set -x

source /common.sh
install_chroot_fail_on_error_trap

# Pillow for pic engraving support
sudo apt-get -y install python-dev python-setuptools libtiff4-dev libjpeg8-dev zlib1g-dev libfreetype6-dev liblcms2-dev libwebp-dev tcl8.5-dev tk8.5-dev python-tk python-pip
pip install Pillow webcolors

# libxml2 for parsing svg files
sudo apt-get -y install python-lxml

# TODO necessary ?
#sudo apt-get -y install firmware-ralink 
# install netconnectd deps (https://github.com/foosel/netconnectd)
#sudo apt-get -y install hostapd dnsmasq logrotate
#sudo update-rc.d -f hostapd remove
#sudo update-rc.d -f dnsmasq remove

pushd /home/pi
  
  #LC Display code
  gitclone OCTOPI_LCD_REPO lcd
  pushd lcd
	
  popd

# TODO safely remove
  # disabled until rewrite
  # update plugin for octoprint
  #sudo -u pi git clone https://github.com/mrbeam/updateplugin.git
  #pushd updateplugin
  #    #sudo -u pi git checkout mrbeam-stable
  #    sudo -u pi /home/pi/oprint/bin/python setup.py install
  #popd
 
  # mrbeam inkscape ext // for svg2gcode plugin
  gitclone OCTOPI_INKEX_REPO mrbeam-inkscape-ext
  pushd mrbeam-inkscape-ext

  popd

popd

# TODO safely remove
# change the hostname to mr beam
#echo mrbeam > /etc/hostname
#sudo sed -i 's@raspberrypi@mrbeam@' /etc/hosts
#sudo sed -i 's@octopi@mrbeam@' /etc/hosts

# enable the lc display at start
sudo update-rc.d lcdisplay defaults 99

# TODO safely remove
# netconnectd configuration
# disable wpa_supplicant
#wpa-roam /etc/wpa_supplicant/wpa_supplicant.conf
#sudo sed -i "s@wpa-roam@#wpa-roam@" /etc/network/interfaces
# enable dhcp client timeout (see installation instructions for netconnectd)
#sudo sed -i "s@#timeout 60@timeout 60@" /etc/dhcp/dhclient.conf
# TODO depends strongly on the config yaml layout - make more agnostic to changes?
#sudo sed -i "s@free: true@free: false@" /etc/netconnectd.yaml
#sudo sed -i -E "s@ssid: .*\$@ssid: MrBeamAP@" /etc/netconnectd.yaml
#sudo sed -i "s@psk: .*\$@psk:@" /etc/netconnectd.yaml
# enable netconnectd at start
#sudo update-rc.d netconnectd defaults 98
