plugins:
    softwareupdate:
        checks:
            octoprint:
                enabled: false
        octoprint_restart_command: sudo service octoprint restart
        environment_restart_command: sudo reboot
        cache_ttl: 60
webcam:
  stream: /webcam/?action=stream
  snapshot: http://127.0.0.1:8080/?action=snapshot
  ffmpeg: /usr/bin/avconv
system:
  actions:
  - name: Shutdown
    command: sudo shutdown -h now
    action: shutdown
    confirm: You are about to shutdown the system.
  - name: Reboot
    command: sudo shutdown -r now
    action: reboot
    confirm: You are about to reboot the system
  - name: Restart OctoPrint
    command: sudo service octoprint restart
    action: restart
    confirm: You are about to restart OctoPrint
