#!/usr/bin/env bash
export BRANCH_OCTOPRINT=mrbeam
export BRANCH_INKEX=dev
export BRANCH_NETCONNECTD=mrbeam
export BRANCH_NETCONNECT_PLUGIN=mrbeam
export BRANCH_LCD=mrbeam

OCTOPI_PATH=$(dirname $(realpath -s $0))
source $OCTOPI_PATH/config
source $OCTOPI_PATH/octopi
