#!/usr/bin/env bash
set -x

# exit script on any error
set -e

# Pillow for pic engraving support
sudo apt-get -y install python-dev python-setuptools libtiff4-dev libjpeg8-dev zlib1g-dev libfreetype6-dev liblcms2-dev libwebp-dev tcl8.5-dev tk8.5-dev python-tk python-pip
pip install Pillow webcolors

# libxml2 for parsing svg files
sudo apt-get -y install python-lxml

sudo apt-get -y install firmware-ralink 
# install netconnectd deps (https://github.com/foosel/netconnectd)
sudo apt-get -y install hostapd dnsmasq logrotate
sudo update-rc.d -f hostapd remove
sudo update-rc.d -f dnsmasq remove

pushd /home/pi
  
  #LC Display code
  sudo -u pi git clone https://github.com/mrbeam/lcd.git
  pushd lcd
      sudo -u pi git checkout ${BRANCH_LCD}
  popd
  
  #netconnectd
  sudo -u pi git clone https://github.com/mrbeam/netconnectd.git
  pushd netconnectd
      sudo -u pi git checkout ${BRANCH_NETCONNECTD}
      sudo python setup.py install
      sudo python setup.py install_extras
  popd
  
  # netdonnectd plugin for octoprint
  sudo -u pi git clone https://github.com/mrbeam/OctoPrint-Netconnectd.git
  pushd OctoPrint-Netconnectd
      sudo -u pi git checkout ${BRANCH_NETCONNECT_PLUGIN}
      sudo -u pi /home/pi/oprint/bin/python setup.py install
  popd
  
  # generic software update plugin for octoprint
  sudo -u pi git clone https://github.com/mrbeam/OctoPrint-SoftwareUpdate.git
  pushd OctoPrint-SoftwareUpdate
      #sudo -u pi git checkout mrbeam-stable
      sudo -u pi /home/pi/oprint/bin/python setup.py install
  popd
  
  # update plugin for octoprint
  sudo -u pi git clone https://github.com/mrbeam/updateplugin.git
  pushd updateplugin
      #sudo -u pi git checkout mrbeam-stable
      sudo -u pi /home/pi/oprint/bin/python setup.py install
  popd
 
  # mrbeam inkscape ext // for svg2gcode plugin
  sudo -u pi git clone https://github.com/mrbeam/mrbeam-inkscape-ext.git
  pushd mrbeam-inkscape-ext
      sudo -u pi git checkout ${BRANCH_INKEX}
  popd


popd

# change the hostname to mr beam
echo mrbeam > /etc/hostname
sudo sed -i 's@raspberrypi@mrbeam@' /etc/hosts
sudo sed -i 's@octopi@mrbeam@' /etc/hosts

# enable the lc display at start
sudo update-rc.d lcdisplay defaults 99

# netconnectd configuration
# disable wpa_supplicant
#wpa-roam /etc/wpa_supplicant/wpa_supplicant.conf
sudo sed -i "s@wpa-roam@#wpa-roam@" /etc/network/interfaces
# enable dhcp client timeout (see installation instructions for netconnectd)
sudo sed -i "s@#timeout 60@timeout 60@" /etc/dhcp/dhclient.conf
# TODO depends strongly on the config yaml layout - make more agnostic to changes?
sudo sed -i "s@free: true@free: false@" /etc/netconnectd.yaml
sudo sed -i -E "s@ssid: .*\$@ssid: MrBeamAP@" /etc/netconnectd.yaml
sudo sed -i "s@psk: .*\$@psk:@" /etc/netconnectd.yaml
# enable netconnectd at start
sudo update-rc.d netconnectd defaults 98
