#!/usr/bin/env bash
set -x

sudo apt-get -y install firmware-ralink 
# install netconnectd deps (https://github.com/foosel/netconnectd)
sudo apt-get -y install hostapd dnsmasq logrotate
sudo update-rc.d -f hostapd remove
sudo update-rc.d -f dnsmasq remove

pushd /home/pi
  
  #LC Display code
  sudo -u pi git clone https://github.com/mrbeam/lcd.git
  
  #netconnectd
  sudo -u pi git clone https://github.com/mrbeam/netconnectd.git
  pushd netconnectd
      sudo python setup.py install
      sudo python setup.py install_extras
  popd
  
  # netdonnectd plugin for octoprint
  sudo -u pi git clone https://github.com/OctoPrint/OctoPrint-Netconnectd.git
  pushd OctoPrint-Netconnectd
      sudo -u pi /home/pi/oprint/bin/python setup.py install
  popd
  
popd

# change the hostname to mr beam
echo mrbeam > /etc/hostname
sudo sed -i 's@raspberrypi@mrbeam@' /etc/hosts
sudo sed -i 's@octopi@mrbeam@' /etc/hosts

# enable the lc display at start
sudo update-rc.d lcdisplay defaults 99

# netconnectd configuration
# disable wpa_supplicant
#wpa-roam /etc/wpa_supplicant/wpa_supplicant.conf
sudo sed -i "s@wpa-roam@#wpa-roam@" /etc/network/interfaces
# enable dhcp client timeout (see installation instructions for netconnectd)
sudo sed -i "s@#timeout 60@timeout 60@" /etc/dhcp/dhclient.conf
# TODO depends strongly on the config yaml layout - make more agnostic to changes?
sudo sed -i "s@free: true@free: false@" /etc/netconnectd.yaml
sudo sed -i -E "s@ssid: .*\$@ssid: MrBeamAP@" /etc/netconnectd.yaml
sudo sed -i "s@psk: .*\$@psk: MrBeam!!@" /etc/netconnectd.yaml
# enable netconnectd at start
sudo update-rc.d netconnectd defaults 98
