#!/usr/bin/env bash
# OctoPi generation script
# This script takes a Raspbian image and adds to it octoprint and verions addons
# Written by Guy Sheffer <guysoft at gmail dot com>
# GPL V3
mkdir -p $OCTOPI_WORKSPACE
mkdir -p $MOUNT_PATH

echo "BEAMIFY OctoPrint"

pushd $OCTOPI_WORKSPACE
  IMG_PATH=mrbeam_build_`date -u +%Y%m%d_%H%M`.img

  rm -f mrbeam*.img
  cp $OPI_IMG $IMG_PATH

  # mount root and boot partition
  sudo mount -o loop,offset=$((512*122880)) $IMG_PATH $MOUNT_PATH
  sudo mount -o loop,offset=$((512*8192)) $IMG_PATH $MOUNT_PATH/boot

  #Edit pi filesystem
  pushd $MOUNT_PATH

    #make QEMU boot (remember to return)
    #sed -i 's@include /etc/ld.so.conf.d/\*.conf@\#include /etc/ld.so.conf.d/\*.conf@' etc/ld.so.conf

    #move OctoPi filesystem files
    cp -av $SCRIPT_PATH/filesystem . 

    #black magic of qemu-arm-static
    cp `which qemu-arm-static` usr/bin
    #cp $CHROOT_SCRIPT_PATH chroot_script
    #chmod 755 chroot_script
    
    #chroot . usr/bin/qemu-arm-static /bin/bash /chroot_script
    #RETVAL=$?
    
    #if [ $RETVAL -eq 0 ]
    #then
        #mr beam stuff
        cp $CHROOT_MRBEAM_PATH chroot_mrbeam
        chmod 755 chroot_mrbeam
        chroot . usr/bin/qemu-arm-static /bin/bash /chroot_mrbeam
        rm chroot_mrbeam
    #else
    #    echo "chroot_script exited with $RETVAL"
    #fi
    
    #cleanup
    #rm chroot_script
    rm -rfv filesystem
  popd
  
  # unmount first boot, then root partition
  sudo umount $MOUNT_PATH/boot
  sudo umount $MOUNT_PATH
  chmod 777 $IMG_PATH
popd

